<?php
define("ACTIVE_CONTESTS_PERMALINK","challenges");
define("PAST_CONTESTS_PERMALINK","past-contests");
define("REVIEW_OPPORTUNITIES_PERMALINK","review-opportunities");
define("CONTEST_DETAILS_PERMALINK","challenge-details");
define("MEMBER_PROFILE_PERMALINK","member-profile");
define("BLOG_PERMALINK","blog");
define("DESIGN_CONTESTS_PERMALINK","design");
define("DEVELOP_CONTESTS_PERMALINK","develop");
define("DATA_CONTESTS_PERMALINK","data");
